Run GEE with independence working correlation
=============================================

# Setup

## Libraries

```{r "setup"}
## Load libraries
## Available from http://cran.r-project.org/web/packages/getopt/index.html
# install.packages("getopt")
library("getopt")

## Available from http://cran.at.r-project.org/web/packages/knitrBootstrap/index.html
# install.packages("knitrBootstrap")
library("knitrBootstrap")

# --- Specify any other libraries you need
# --- Not needed (since you load them in template.R), but good for the report
# --- Anyhow, just copying and pasting from template.R is good
## gee
# install.packages("geepack")
library("geepack")

## for mclapply
library("parallel")
```

## Directories

```{r "directories"}
## Chr
chr <- paste0("chr", opt$chrnum)
chrnum <- as.numeric(opt$chrnum)

## Create dir to save files
if(opt$verbose) message("Creating directories")
ddir <- file.path(opt$dirResult, opt$project, chr) # data directory (might change say if step2 uses the results from step2)
wdir <- file.path(opt$dirResult, opt$project, chr, opt$results) # working dir
dir.create(wdir, recursive=TRUE)

## Want to save some 'object'? Use:
# save(object, file=file.path(wdir, "object.Rdata"))
```


# GEE independence


```{r "rungee", dev="CairoPNG"}
## Load data
load(file.path(ddir, "geeAR1", "covdata.used.Rdata"))
load(file.path(ddir, "geeAR1", "pairs.used.Rdata"))


## Run GEE
idx <- seq_len(length(covdata.used))
## testing:
#idx <- 1:2
myGEE <- function(i, corstr) {
	geeglm(coverage ~ sampleDepth + group + region, id = sample, data = covdata.used[[i]], family = gaussian, corstr = corstr)
}
myGEE.int <- function(i, corstr) {
	geeglm(coverage ~ sampleDepth + group * region, id = sample, data = covdata.used[[i]], family = gaussian, corstr = corstr)
}

## GEE Ind
if(opt$verbose) message(paste(Sys.time(), "running GEE with AR1"))
geeInd <- mclapply(idx, myGEE, corstr="independence", mc.cores=20)
names(geeInd) <- names(covdata.used)[idx]
save(geeInd, file=file.path(wdir, "geeInd.Rdata"))

## GEE Ind - int
if(opt$verbose) message(paste(Sys.time(), "running GEE with AR1 - interaction"))
geeInd.int <- mclapply(idx, myGEE.int, corstr="independence", mc.cores=20)
names(geeInd.int) <- names(covdata.used)[idx]
save(geeInd.int, file=file.path(wdir, "geeInd.int.Rdata"))

## Show an example:
geeInd[[1]]
summary(geeInd[[1]])
geeInd.int[[1]]
summary(geeInd.int[[1]])


## Extract region2 coef estimate, st.error, and Wald stat
myGEE.stat <- function(y) {
	beta <- c(coef(y)["regionregion2"], y$geese$gamma)
	## Assumes that geeglm(std.err="san.se") which is the default value
	vbeta <- sqrt(c(y$geese$vbeta[6, 6], y$geese$vgamma))
	wald <- (beta/vbeta)^2
	pval <- 1 - pchisq(wald, df=1)
	df <- data.frame(coef=c("region2", "gamma"), estimate=beta, stderr=vbeta, wald=wald, pval=pval)
	rownames(df) <- seq_len(nrow(df))
	return(df)
}
geeInd.stat <- lapply(geeInd, myGEE.stat)
save(geeInd.stat, file=file.path(wdir, "geeInd.stat.Rdata"))

## Extract region2 coef estimate, interaction coef estiamtes, st.error, and Wald stat
myGEE.int.stat <- function(y) {
	beta <- c(coef(y)[c("regionregion2", "groupCO:regionregion2", "groupETOH:regionregion2")], y$geese$gamma)
	## Assumes that geeglm(std.err="san.se") which is the default value
	vbeta <- sqrt(c(y$geese$vbeta[6, 6], y$geese$vbeta[9, 9], y$geese$vbeta[10, 10], y$geese$vgamma))
	wald <- (beta/vbeta)^2
	pval <- 1 - pchisq(wald, df=1)
	df <- data.frame(coef=c("region2", "groupCO:region2", "groupETOH:region2", "gamma"), estimate=beta, stderr=vbeta, wald=wald, pval=pval)
	rownames(df) <- seq_len(nrow(df))
	return(df)
}

geeInd.int.stat <- lapply(geeInd.int, myGEE.int.stat)
save(geeInd.int.stat, file=file.path(wdir, "geeInd.int.stat.Rdata"))


## Show an example:
geeInd.stat[[1]]
geeInd.int.stat[[1]]
```










# Reproducibility

Date the report was generated.

```{r "reproducibility1", echo=FALSE}
## Date the report was generated
Sys.time()
```

Wallclock time spent generating the report.

```{r "reproducibility2", echo=FALSE}
## Processing time in seconds
totalTime <- diff(c(startTime, Sys.time()))
round(totalTime, digits=3)
```

`R` session information.

```{r "reproducibility3", echo=FALSE}
## Session info
sessionInfo()
```
